/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.mvc.view;
import edu.ijse.mvc.control.*;
import java.sql.SQLException;
import edu.ijse.mvc.dto.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author user
 */
public class OrderView extends javax.swing.JFrame {
    private ItemController itemcontroller;
    private CustomerController customercontroller;
    private ArrayList<OrdersDetailDto> OrderDetailDtos;
    private OrdersController ordersController;
    /**
     * Creates new form OrderView
     */
    public OrderView() throws ClassNotFoundException, SQLException {
        initComponents();
        itemcontroller = new ItemController();
        customercontroller = new CustomerController();
        OrderDetailDtos = new ArrayList<>();
        ordersController = new OrdersController();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lbltitle = new javax.swing.JLabel();
        lblorderid = new javax.swing.JLabel();
        lblcustomerid = new javax.swing.JLabel();
        txtorderid = new javax.swing.JTextField();
        txtcustomerid = new javax.swing.JTextField();
        btnsearchcustid = new javax.swing.JButton();
        btnsearchitemid = new javax.swing.JButton();
        lblitemid = new javax.swing.JLabel();
        txtitemid = new javax.swing.JTextField();
        lblitemdata = new javax.swing.JLabel();
        lblcustomerdata = new javax.swing.JLabel();
        lbldiscount = new javax.swing.JLabel();
        txtdiscount = new javax.swing.JTextField();
        lblqty = new javax.swing.JLabel();
        txtqty = new javax.swing.JTextField();
        btnadditem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblorders = new javax.swing.JTable();
        btnplaceorder = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitle.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("PlaceOrder");

        lblorderid.setText("Order ID");

        lblcustomerid.setText("Customer ID");

        txtcustomerid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustomeridActionPerformed(evt);
            }
        });

        btnsearchcustid.setText("Search");
        btnsearchcustid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchcustidActionPerformed(evt);
            }
        });

        btnsearchitemid.setText("Search");
        btnsearchitemid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchitemidActionPerformed(evt);
            }
        });

        lblitemid.setText("Item ID");

        txtitemid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtitemidActionPerformed(evt);
            }
        });

        lbldiscount.setText("Discount");

        txtdiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiscountActionPerformed(evt);
            }
        });

        lblqty.setText("Qty");

        txtqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtyActionPerformed(evt);
            }
        });

        btnadditem.setText("Add");
        btnadditem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadditemActionPerformed(evt);
            }
        });

        tblorders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblorders);

        btnplaceorder.setText("Place Order");
        btnplaceorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplaceorderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblcustomerid)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtcustomerid, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                            .addComponent(txtitemid)
                                            .addComponent(txtdiscount)))
                                    .addComponent(lblitemid)
                                    .addComponent(lbldiscount))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(lblqty, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnadditem))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnsearchcustid)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblcustomerdata, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 80, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnsearchitemid)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblitemdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblorderid)
                                .addGap(40, 40, 40)
                                .addComponent(txtorderid, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnplaceorder)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblorderid)
                    .addComponent(txtorderid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcustomerid)
                            .addComponent(txtcustomerid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsearchcustid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblitemid)
                            .addComponent(txtitemid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsearchitemid)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblcustomerdata, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblitemdata, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldiscount)
                    .addComponent(txtdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblqty)
                    .addComponent(btnadditem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnplaceorder)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcustomeridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustomeridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustomeridActionPerformed

    private void txtitemidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtitemidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtitemidActionPerformed

    private void txtdiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiscountActionPerformed

    private void txtqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtyActionPerformed

    private void btnsearchitemidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchitemidActionPerformed
           searchItem();        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchitemidActionPerformed

    private void btnsearchcustidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchcustidActionPerformed
           searchCustomer();        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchcustidActionPerformed

    private void btnadditemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadditemActionPerformed
      addToTable() ;       // TODO add your handling code here:
    }//GEN-LAST:event_btnadditemActionPerformed

    private void btnplaceorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplaceorderActionPerformed
           placeOrder();        // TODO add your handling code here:
    }//GEN-LAST:event_btnplaceorderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new OrderView().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(OrderView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(OrderView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadditem;
    private javax.swing.JButton btnplaceorder;
    private javax.swing.JButton btnsearchcustid;
    private javax.swing.JButton btnsearchitemid;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcustomerdata;
    private javax.swing.JLabel lblcustomerid;
    private javax.swing.JLabel lbldiscount;
    private javax.swing.JLabel lblitemdata;
    private javax.swing.JLabel lblitemid;
    private javax.swing.JLabel lblorderid;
    private javax.swing.JLabel lblqty;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JTable tblorders;
    private javax.swing.JTextField txtcustomerid;
    private javax.swing.JTextField txtdiscount;
    private javax.swing.JTextField txtitemid;
    private javax.swing.JTextField txtorderid;
    private javax.swing.JTextField txtqty;
    // End of variables declaration//GEN-END:variables

    private void searchItem() {
      try{
          String id = txtitemid.getText();
          ItemDto dto = itemcontroller.searchItem(id);
          if(dto!=null){
              lblitemdata.setText(dto.getItemCode()+" "+dto.getDescription()+" "+dto.getPackSize()+" "+dto.getUnitPrize()+" "+dto.getQtyOnHand());
          }
          else{
              lblitemdata.setText("Item Not Found");
          }
      }catch(Exception e){
      }
    }

    private void searchCustomer() {
       String id = txtcustomerid.getText();
       CustomerDto dto = customercontroller.searchCustomer(id);
       if(dto != null){
           lblcustomerdata.setText(dto.getCustID()+" "+dto.getName());
       }
       else{
           lblcustomerdata.setText("Customet Not Found");
       }
    }

    private void loadTable() {
        String columns [] = {"Item Code", "QTh", "Discount"};
        DefaultTableModel dtm = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblorders.setModel(dtm);
    }

    private void addToTable() {
        try {
        OrdersDetailDto orderdetaildto = new OrdersDetailDto(txtorderid.getText(), txtitemid.getText(),Integer.parseInt(txtqty.getText()),Integer.parseInt(txtdiscount.getText()));
        OrderDetailDtos.add(orderdetaildto);
        
        Object [] rowdata = {orderdetaildto.getItemCode(),orderdetaildto.getQoh(), orderdetaildto.getDiscount()};
        DefaultTableModel dtm =  (DefaultTableModel) tblorders.getModel();
        dtm.addRow(rowdata);
        clear();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Check Again");
        }
    }
    
    
    private  void clear(){
        txtitemid.setText("");
        txtdiscount.setText("");
        txtqty.setText("");
        lblitemdata.setText("");
    }
    


    private void placeOrder() {
     try{
         OrdersDto ordersDto = new OrdersDto(); 
         ordersDto.setCustID(txtcustomerid.getText());
         ordersDto.setOrderID(txtorderid.getText());
         
         SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
         String date = sdf.format(new Date());
         ordersDto.setDate(date);
         
         
         String resp = ordersController.placeOrder(ordersDto, OrderDetailDtos);
         JOptionPane.showMessageDialog(this, resp);
     }catch(Exception e){
         //JOptionPane.showMessageDialog(this, resp);
     }

    }
}
